namespace :db do
  desc 'Load initial ART courses into database'
  task :courses => :environment do
    # Taken from 2009 - 2010 Catalog -- December 7th, 2009
    # http://www.belmont.edu/catalog/undergrad2009jun/cvpa/art/courses.html
    # http://www.belmont.edu/catalog/undergrad2009jun/cvpa/art/courses-3000up.html
    
    courses = [
      { 'course_number' => '1010', 'credit_hours' => '3', 'name' => '2-D Princeiples of Design', 'course_description' => 'An introduction to the visual elements and principles of two-dimensional design through projects that emphasize discovery through experimentation, research, analysis and problem solving. The projects emphasize the exploration of design issues in black, white and grays (values). Color is introduced through the correlation of value to hue.'},
      { 'course_number' => '1011', 'credit_hours' => '3', 'name' => '2D:Principles of Color', 'course_description' => 'An introduction to subtractive color mixtures, systems of color order and notation, and the color solid. All of the characteristics of color and many associated phenomena are examined and put into practice as design elements in the context of increasingly complex visual problems.' },
      { 'course_number' => '1030', 'credit_hours' => '3', 'name' => '3-D Design', 'course_description' => 'The purpose of this course is to introduce the student to the basic principles of 3-dimensional design. This course will combine design theory with projects created by each student. Students will explore the basic components of 3-dimensional art which includes subject, form, and content. A variety of materials and techniques will be introduced to the student including casting, modeling, additive and subtractive sculpture and fabrication. Materials used will include plaster, wire, clay, wood, paint, paper, etc. Students should bring unique interpretations to their projects. Discussions centered around 3-dimensional design and creative ideas should help foster artistic awareness and understanding of basic 3-dimensional concepts. ' },
      { 'course_number' => '1030', 'credit_hours' => '3', 'name' => 'Drawing I ', 'course_description' => 'This course is an introduction to basic drawing materials, practices, and concepts. The class will focus on the process of perception in particular as a means to achieve a successful drawing. Various techniques of using graphite, pen, and conte crayon will be demonstrated, and the use of line, value shading, and composition will be constantly emphasized and practiced, using assorted classroom and outdoor arrangements as a basis for study. Students who successfully complete the course should be able to use contour line, value shading, gesture, and other techniques to accurately represent what they see. ' },
      { 'course_number' => '1040', 'credit_hours' => '3', 'name' => 'Figure Drawing I ', 'course_description' => 'The course practice will consist primarily of observing and drawing the human figure in a wide range of poses, lighting conditions and time frames, and learning to use a variety of media and techniques. Special emphasis will be on placing a figure within a composition and using correct anatomical proportions. Additional out-of-class drawings with figurative elements will be assigned in order to further develop perceptual sensitivities. Students completing the course should be able to draw the human figure using conte crayon, charcoal and graphite, as well as understand several historical approaches used to make successful figure drawings.' },
      { 'course_number' => '1050', 'credit_hours' => '3', 'name' => 'Paiting I', 'course_description' => 'An emphasis on basic painting skills and the exploration of techniques and materials. Exercises include: chiaroscuro, flat pattern design, direct painting (alla prima), glazing, and paint application techniques. Design basics, color mixing, and problem solving skills are stressed. Mediums used are acrylic and oil based.' },
      { 'course_number' => '1060', 'credit_hours' => '3', 'name' => 'Photography I', 'course_description' => 'An introduction to the basics of black and white photography. This class emphasizes the basic parts and operation of an SLR (manual) camera, black and white film processing, and darkroom use. Students will study the basics of composition, design, lighting, printing, processing, and final print presentation. Students will learn to develop film, process prints, and other printing controls such as dodging, burning, and the use of filters. Concentration is on photography as a fine art medium. Students must have a 35mm manual control camera. ' },
      { 'course_number' => '1070', 'credit_hours' => '3', 'name' => 'Clay I', 'course_description' => 'This course provides an introduction to the design and creation of ceramic forms. Students will be introduced to a variety of clay bodies, basic construction methods---including pinch and coil pots, slab-building, and wheel throwing---and the demonstration of different firing techniques. Additional focus will be made on the use of glazes, slips, and engobes. Students will gain a visual awareness of the aesthetics of original ceramic pottery and/or sculpture, and learn to identify and use the techniques, tools, processes, and materials associated with them. ' },
      { 'course_number' => '1080', 'credit_hours' => '3', 'name' => 'Sculpture I', 'course_description' => 'The emphasis in this course is on the development of each individual\'s visual sense and its expression in sculptural form. The student will explore sculptural materials, techniques, and concepts in a more detailed and concentrated manner. More advanced sculptural media will be introduced including stone carving, woodworking, modeling, and fabrication. The student will be encouraged to explore in more conceptual depth a medium they find to be of interest. There will be several opportunities to meet and talk to artists, visit their studios and visit art galleries in the community. Students will also be exposed to historical and contemporary artists with an emphasis on sculptors.' },
      { 'course_number' => '1090', 'credit_hours' => '3', 'name' => 'Printmaking I', 'course_description' => 'An introduction to the techniques, materials, and methods used in intaglio, relief, and monotypes.' },
      { 'course_number' => '1110', 'credit_hours' => '3', 'name' => 'Color Theory', 'course_description' => 'A study of advanced color theories and their application as well as an investigation of physical aspects of color perception and manipulation using subtractive color processes. Projects will focus on the emotional impact of color combinations and a more thorough understanding of pigment properties. The course will also include the compositional principles of gestalt, rhythm, variety, repetition, balance, emphasis, and proportion. Extensive outside work required.' },
      { 'course_number' => '1400', 'credit_hours' => '3', 'name' => 'Introduction to Digital Imaging', 'course_description' => 'This introductory course in digital imaging will introduce students to the basic Macintosh hardware and operating system. In addition, the course is a survey of basic animation, Adobe Photoshop and Adobe Illustrator. The course also includes basic bookbinding as well as panoramic and large format digital printing techniques.' },
      { 'course_number' => '1450', 'credit_hours' => '3', 'name' => 'Design Communications for Non-Majors', 'course_description' => 'This is an introductory course to the profession of graphic design specifically geared towards non-majors. Emphasis is placed on design principles, design elements, visual language, the overall design process, and introduction to technology. Students will be introduced to the profession through investigation of case studies, examination of design artifacts and the client / designer relationship. Students will not only learn about the design process including research, brainstorming, and conceptual problem-solving but have opportunities to create their own projects implementing basic design production utilizing various tools / mediums including the Macintosh computer and basic industry software. Experience in the Macintosh platform not required although recommended.' },
      { 'course_number' => '1700', 'credit_hours' => '3', 'name' => 'Principles of Web Page Design', 'course_description' => 'This course is an integrated introduction to web page design, covering both its aesthetic and technical aspects. The topics introduced will include: Internet Protocol fundamentals, HTML, page layout, imaging, color, typography, embedded technologies, file types, portability and performance.' },
      { 'course_number' => '2000', 'credit_hours' => '3', 'name' => 'Art Experience', 'course_description' => 'An introduction to experiencing and understanding humanity\'s heritage in the visual arts. Primary emphasis will be made on analyzing the basic form and content of a variety of art and architecture from all periods, styles, and cultures. All students will be expected to gain working knowledge of an aesthetic vocabulary, and be able to use it and related concepts to evaluate works of art. Students should also gain a heightened appreciation for the complexities of visual experience, and be capable of continuing further study in the field of art.' },
      { 'course_number' => '2005', 'credit_hours' => '3', 'name' => 'Introduction to Art Education', 'course_description' => 'ntroduces students to the historical foundations and contemporary practice of art education. Special emphasis is given to the development of conceptual understandings and skills in aesthetics, art criticism, art history, visual culture and art production, including digital media and computer technologies. Students will investigate fundamental issues in curriculum, instruction, and assessment, and will explore career opportunities in both schools and community art settings through field observations. Introduction to Art Education serves as a prerequisite for further study in the Art Education major.' },
      { 'course_number' => '2030', 'credit_hours' => '3', 'name' => 'Drawing II', 'course_description' => ' This course is an expansion of the visual concepts, materials and practices introduced in Drawing I. Emphasis will be given to the integration of visual elements with the personal expression of ideas. Both conventional and unconventional techniques for combining drawing media will be described and demonstrated. The course media will include colored pencils, inks and oil pastels. Class projects will be based on studio set-ups, photos and other printed materials, and imaginative sources. Students will be further prepared to develop a personal drawing style by using a range of abstract and realistic forms of expression.' },
      { 'course_number' => '2040', 'credit_hours' => '3', 'name' => 'Figure Drawing II', 'course_description' => 'This course continues the basic disciplines learned in Figure Drawing I. Students will also learn to integrate color with more perceptive interpretation of the human figure. A wider variety of drawing media will be used, including oil pastels, colored pencils, sharpies and pastels. Equal emphasis will be placed on creating expressive drawings and on using realistic anatomical proportions.' },
      { 'course_number' => '2050', 'credit_hours' => '3', 'name' => 'Painting II', 'course_description' => 'A continuing exploration of the painting process, with a strong emphasis on technical development and experimentation with various painting media. The focus will be on developing a visual language through painting, developing individual skills in particular painting media, and developing concepts into finished works. This course will explore the visual conceptions of such styles as representational, abstract, and/or nonrepresentational working in the media of oil, acrylic, mixed media, and/or watercolor. Students will continue to identify and use the techniques, tools, processes, and materials associated with these media, and begin to explore various ways of choosing subject matter and developing ideas through the use of various painting media and compositional means. An emphasis will be put on individual creative expression.' },
      { 'course_number' => '2060', 'credit_hours' => '3', 'name' => 'Photography II', 'course_description' => 'Intermediate study of black and white processes. Students must have a 35mm camera with manual controls. This course is for the student previously experienced with manual camera exposures and basic black and white processing. The class will explore secondary levels of black and white materials and processing, color/digital prints, collage techniques, book making and altered images. Emphasis is placed on creativity and the quality of finished prints. There will be an emphasis on improving composition, concentrating the focus of ideas, viewer reaction to finished prints, and evaluating the quality of the final image.' },
      { 'course_number' => '2070', 'credit_hours' => '3', 'name' => 'Clay II', 'course_description' => 'A continuation of the work in clay in which the student concentrates on handbuilding, sculpture, and/or wheel throwing. A refinement of Clay I techniques plus the possible introduction to raku (including firing in a modern raku kiln). Clay I techniques are to be refined with an emphasis on individual creative expression. Students will continue to explore the creative possibilities of original ceramic pottery and/or sculpture with a greater emphasis on decorating and glazing techniques.' },
      { 'course_number' => '2080', 'credit_hours' => '3', 'name' => 'Sculpture II', 'course_description' => 'Intensive exploration of sculptural concepts through the use of selected techniques and materials, with an emphasis on the development of individual expression.' },
      { 'course_number' => '2090', 'credit_hours' => '3', 'name' => 'Printmaking II', 'course_description' => 'An introduction to the processes of black and white and color lithography.' },
      { 'course_number' => '2100', 'credit_hours' => '3', 'name' => 'The Design Experience', 'course_description' => 'This course is an introduction to experiencing and understanding the role of design in our visual culture. Emphasis is on the evolution of the visual language of design throughout human history, based on the impact of technology on design\'s methods, materials and styles. Students will examine their role as participants in the culture of design - through production, consumption and interpretation - and should gain a heightened appreciation for the complex ways that aesthetics, the creative process, and the discipline of design itself affect their knowledge of all aspects of visual culture.' },
      { 'course_number' => '2150', 'credit_hours' => '3', 'name' => 'Watercolor Painting I', 'course_description' => 'Familiarizes students with the techniques and approaches used in watercolor painting. Additional mediums such as gouache, ink, tissue paper, and pastels as mixed media components will be introduced. Summer only.' },
      { 'course_number' => '2160', 'credit_hours' => '3', 'name' => 'Art for the Educator: Appreciation & Application', 'course_description' => 'This course provides a broad overview of visual art for students who plan to work as educators in schools, churches, and other community agencies. The course includes elements drawn from art history, art appreciation, and art education. Students will demonstrate written and oral competencies in these areas. ART 2160 completes the art component of MUH 2140 Arts for Education, for those students who have already completed MUH 2000 or its transfer equivalent.' },
      { 'course_number' => '2410', 'credit_hours' => '3', 'name' => 'Introduction to Design Principles', 'course_description' => 'Design is the use of visual forms (words and images) that are used to convey information to diverse audiences. This course is the first in a sequence of Design Communications courses. Students will explore the use of basic design principles, design elements, introductory theory and brainstorming techniques to solve basic communication problems without the use of a computer. Emphasis will be on obeservation, analysis, design process, terminology, creative thinking, problem-solving, execution and craftmanship. Several projects may be considered as portfolio pieces.' },
      { 'course_number' => '2411', 'credit_hours' => '1', 'name' => 'Sophomore Production Workshop', 'course_description' => 'Emphasizes technology and production skills for print graphics. This course must be taken twice; once each semester during the sophomore year.' },
      { 'course_number' => '2420', 'credit_hours' => '3', 'name' => 'Design Systems', 'course_description' => 'One in a series of Design Communications courses that focuses on the development of a professional-level design portfolio. Projects include multiple-piece design, introduction to product identity, and an introduction to three dimensional graphic design. The course also emphasizes raster imaging and covers compositing of graphic elements in advanced page-layout applications. Extensive outside work is required.' },
      { 'course_number' => '2420', 'credit_hours' => '3', 'name' => 'Typography', 'course_description' => 'A combined lecture and studio course covering the history, terminology and use of typography in the design communications industry. Type sensibility is often used as the measure of professional design acumen, therefore this course should be taken early in design series in order to integrate the knowledge into upper-level core design courses. Students will use computer typography applications as well as studio techniques to complete exercises and problems in typographic communications. Projects and exercises will range from the examination of individual letterforms to organization of a large volume of text in page layouts. Emphasis will be placed on typographic production and terminology. Course software will include current industry technology.' },
      { 'course_number' => '2450', 'credit_hours' => '3', 'name' => 'Interactive Media', 'course_description' => 'This is an introduction to Interactive Media. Topics include: animation, scripting and delivery of vector based interactive media. Emphasis is on we-based media applications. Applications used include Photoshop, Dreamweaver, and Illustrator. The course will emphasize the software application Macromedia Flash.' },
      { 'course_number' => '2500', 'credit_hours' => '3', 'name' => 'DIgital Photography I', 'course_description' => 'An exploration of the medium of digital photography through various camera and computer techniques. Students will examine digital photography through the use of digital cameras, digital negatives and digital prints. The digital negatives will be used to print images by various techniques including, but not limited to, cyanoptype, Van Dyke Brown and palladium. Adobe Photoshop will be used as the computer software for this class. Prerequisites include previous experience with photography and the computer.' },
      { 'course_number' => '2800', 'credit_hours' => '3', 'name' => 'Art History I', 'course_description' => 'This is a general survey of the history of Western art and architecture from the pre-historic through the mid-Gothic period. Particular emphasis will be made on the stylistic achievements of the Graeco-Roman and Gothic eras. The primary course objective will be placed on students learning to make distinctions between the various historical styles as well as writing about the purposes of these styles. All students completing the course should be able to identify and discuss aspects of the basic form and content of any of the styles according to specific periods, schools or artists, and will complete a special research topic or project within a chosen area of interest.' },
      { 'course_number' => '2810', 'credit_hours' => '3', 'name' => 'Art History II', 'course_description' => 'This is the second part of a general survey of the history of Western art and architecture, and covers the Late Gothic to the Modernist era. Particular emphasis will be made on the stylistic achievements of the Renaissance and the 19th century. The primary course objectives remain the same in principle as ART 2800.' },
      { 'course_number' => '3030', 'credit_hours' => '3', 'name' => 'Drawing III: Multimedia', 'course_description' => 'An intensive exploration of a wide range of drawing media, with emphasis on experimentation, the creation of a visual style, and the use of drawing as a means of personal expression. Students will be required to contract for a specific number of drawings to be completed during the term.' },
      { 'course_number' => '3040', 'credit_hours' => '3', 'name' => 'Figure Drawing III', 'course_description' => 'A continuation of studio practices from previous figure courses with added emphasis on exploring the expressive possibilities of the figure. Students will combine and mix a variety of drawing and painting media and papers and techniques in order to complete a portfolio of figurative work that reflects variety of theme and interpretation.' },
      { 'course_number' => '3050', 'credit_hours' => '3', 'name' => 'Painting III', 'course_description' => 'Advanced skill development in painting, with continued experimentation in a wider variety of methods and materials, and an emphasis on exploration in an individual area of interest. Students are expected to define and carry out projects based on their specific objectives. The focus will be on the encouragement and development of the student\'s personal direction. The use of color, content, composition, and emotional impact will be stressed. Students will focus on creativity of expression through conceptual and technical experimentation in a variety of painting media.' },
      { 'course_number' => '3060', 'credit_hours' => '3', 'name' => 'Photography III', 'course_description' => 'This course is an intermediate-level study of photography. Students will be required to make an intensive investigation of digital, black-and-white, and alternative photographic processes. Course projects will enable students to use fiber-based papers, toning, medium format cameras, digital negatives and alternative processes such as cyanotype and Van Dyke Brown prints. Emphasis will be made on the quality of visual ideas, the audience-response to the image, and the evaluation of both technical and aesthetic qualities in the finished prints.' },
      { 'course_number' => '3070', 'credit_hours' => '3', 'name' => 'Clay III', 'course_description' => 'Advanced study in the techniques and concepts of the work in clay. A continuation of the work done in Clay II with the refinement of a personal approach to clay, plus the possible introduction to or continued instruction in clay and glaze formulation, alternative firing methods, and/or the loading and firing of electric kilns. Concentration in this course may be on wheel throwing, sculpture, and/or handbuilding techniques with students beginning to develop their own personal approach to working with clay and decorating original ceramic ware.' },
      { 'course_number' => '3080', 'credit_hours' => '3', 'name' => 'Sculpture III', 'course_description' => 'This course will focus on each student\'s development in the conceptual realm with emphasis on material and technical exploration. In addition to tailoring to the individual needs of students, this course will also require the study of pertinent text and timely and culturally relevant work.' },
      { 'course_number' => '3090', 'credit_hours' => '3', 'name' => 'Printmaking III', 'course_description' => 'Besides continuing and developing techniques in traditional printmaking methods, this course will emphasize experimentation and personal exploration into one or two specific methods as well as introducing photographic techniques and dimensional prints.' },
      { 'course_number' => '3150', 'credit_hours' => '3', 'name' => 'Watercolor Painting II', 'course_description' => 'A deeper investigation and continuation of special techniques and approaches introduced in Watercolor Painting I. Mastering the application of certain techniques alongside the sensitive use of spontaneous and unpredictable outcomes will help students to better understand the medium. Summer only.' },
      { 'course_number' => '3160', 'credit_hours' => '3', 'name' => 'Mixed Media Painting', 'course_description' => 'Creating with a combination of several different media in a single work of art. Students will incorporate paint, collage, transfers, found objects, and more as they create their works, offering students the opportunity to explore a new approach to image making on the flat surface. Summer only.' },
      { 'course_number' => '3410', 'credit_hours' => '3', 'name' => 'Linear Design', 'course_description' => 'One of a core series of Design Communications courses that focuses on the development of a professional-level design portfolio. The stage of design requires a portfolio review prior to registration. Projects include publication design, web-site design, and introduction to visual rhetoric. This course requires proficiency in working with and combining raster-based and vector-based digital imagery. Extensive outside work is required.' },
      { 'course_number' => '3411', 'credit_hours' => '1', 'name' => 'Junior Production Workshop', 'course_description' => 'Emphasizes technology and production skills for web and multimedia. This course must be taken twice; once each semester during the junior year.' },
      { 'course_number' => '3420', 'credit_hours' => '3', 'name' => 'Information Design', 'course_description' => 'The course will emphasize the communication of ideas within the framework of Information Design, which seeks to edify more than to persuade. Students will examine how people read and learn information, and navigate through a space- a book, the web, or a physical space. Problems will be complex and multi-faceted such as a redesign of an identity system, navigational system, and informational signage for hypothetical clients. Students will be introduced to the study of semiotics as well as a brief historical perspective of information and environmental design fields. Emphasis will be on research with groups and individual work. Extensive outside work will be expected. The stage of design requires passing portfolio review.' },
      { 'course_number' => '3430', 'credit_hours' => '3', 'name' => 'Illustration I', 'course_description' => 'This course is an introduction to Illustration in the graphic design industry. Emphasis is on problem solving within the context of a client communication problem and working relationships with Creative Directors. This course requires proficiency in basic design skills, drawing, figure drawing, and painting. Extensive outside work is required.' },
      { 'course_number' => '3440', 'credit_hours' => '3', 'name' => 'History and Philosophy of Design', 'course_description' => 'Students will examine the history and relevant theory of visual communication and graphic design including its historical relationship to the larger culture in which it functions. In viewing graphic design beyond the aesthetic, emphasis will be placed on its role in areas such as commerce, culture, propaganda, ideology and the social / political arenas. The underlying themes will be technological influence on communication and the evolution of visual form and language. This lecture course combines readings, discussions, and practical application of theory / concepts through written assignments and possible creation of visual artifacts. Gen. Ed. Designation: GS (G – Global Studies).' },
      { 'course_number' => '3450', 'credit_hours' => '3', 'name' => 'Illustration II', 'course_description' => 'Planning and rendering of advertising and editorial illustrations in various media. Projects include creating imagery for such formats as publications, editorial, and packaging design. This course requires proficiency in basic skills, drawing, figure drawing, and painting. Extensive outside work is required.' },
      { 'course_number' => '3650', 'credit_hours' => '3', 'name' => 'Museum Studies', 'course_description' => 'Introduction to the philosophy, purposes, structure, historical development and future of museums. Examines functions of collection, conservation, research, exhibition/interpretation, and social/cultural services; museum field growth.' },
      { 'course_number' => '3660', 'credit_hours' => '3', 'name' => 'Art History Research and Methodology', 'course_description' => 'An intensive study of the nature of art history as an intellectual discipline and of the approaches scholars have taken to various art historical problems. Attention as well to principles of current art historical research and writing. Recommended for juniors who have declared art history as a major.' },
      { 'course_number' => '3810', 'credit_hours' => '3', 'name' => 'Elementary Art Education', 'course_description' => 'Examines the elementary school culture and the practical application of child development theories to the development of thematic units of study. Students will explore age-appropriate materials and processes, develop strategies for facilitating learning and develop comprehensive lesson plans as a basis for micro-teaching in local elementary schools.' },
      { 'course_number' => '3820', 'credit_hours' => '3', 'name' => 'Secondary Art Education', 'course_description' => 'Examines middle and high school cultures and the aesthetic development of the pre-adolescent and adolescent learner. Students will explore media and processes appropriate for the secondary student, and develop comprehensive, concept-driven lesson plans as a basis for micro-teaching in local secondary schools.' },
      { 'course_number' => '4015', 'credit_hours' => '3', 'name' => 'Art Senior Captsone', 'course_description' => ' Students will reflect on and assess their educational experiences to prepare for their transition to life beyond the university. Among the primary course questions are: \"What is a Meaningful Life?\" and \"What is my role in choosing and creating that life?\" Potential answers to these and related questions will be made through a series of assignments and projects which require intentional thinking, discussing, writing and other creative activities, both in and out of class. This course is offered in the fall semester only. Taken in the Fall semester prior to Spring graduation only.' },
      { 'course_number' => '4030', 'credit_hours' => '3', 'name' => 'Drawing IV', 'course_description' => 'A continuation of the creative processes of ART 3030, with the additional requirement of developing and completing a body of thematically-related drawings. Students will further investigate media, scale, and surface qualities while refining their choice and understanding of subject matter, concept, and intended audience. Students will also concentrate on defining their drawing as sketches, illustrations, and/or finished works.' },
      { 'course_number' => '4050', 'credit_hours' => '3', 'name' => 'Painting IV', 'course_description' => 'This is an independent studies course in painting in which the content of the course is planned by the student under the supervision of the instructor. There should be a continuation of concerns from Painting III with an emphasis on point of view and image making in painting. Students should continue to focus on creativity of expression through conceptual and technical experimentation in a variety of painting media. ' },
      { 'course_number' => '4060', 'credit_hours' => '3', 'name' => 'Photography IV', 'course_description' => 'Intense advanced study of black and white, digital and/or alternative photographic processes. There will be an emphasis on nurturing a photographically self-reliant individual with independent visual images. Students will develop their own ideas into visual projects with an emphasis on the quality and variety of a final portfolio.' },
      { 'course_number' => '4070', 'credit_hours' => '3', 'name' => 'Clay IV', 'course_description' => 'Students in this course will continue to create an individual relationship with clay and its different stages, on and off the wheel. They will find a focus of direction to work on, one which will expand on the individual\'s communication skills. Students will be further exposed to historical and contemporary work from around the world.' },
      { 'course_number' => '4090', 'credit_hours' => '3', 'name' => 'Printmaking IV', 'course_description' => 'Advanced study in one specific method of printmaking. This course emphasizes experimentation and development of the student\'s personal approach to the medium.' },
      { 'course_number' => '4410', 'credit_hours' => '3', 'name' => 'Narrative and Advocacy Design', 'course_description' => 'This is a course in which students will find their design voice. The underlying theme will be narrative (linear and non-linear) as we investigate the designer’s role and responsibility within society. Students will explore a range of issues from recycling, sustainability and consumer consumption to community involvement and relationships with not-for-profit organizations through creative projects and investigation into contemporary and historical sollutions. Additional opportunities for basic exploration in media software applications creating linear narratives will occur through project solutions. Requires passing annual portfolio review prior to registration. Extensive outside work will be required.' },
      { 'course_number' => '4420', 'credit_hours' => '3', 'name' => 'Identity and Branding', 'course_description' => 'The final in a core series of Design Communications courses focusing on the development of a professional-level design portfolio. Projects include the development of a full-scale corporate identity program including graphics standards manual and packaging and/or display design. Extensive outside work is required.' },
      { 'course_number' => '4490', 'credit_hours' => '3', 'name' => 'Design Administration', 'course_description' => 'This course is the study of coordination, management and administration of the operations of a graphic design business. The content of this course includes management, project coordination, technical issues and creative issues. Management topics will include business operations such as personnel supervision, organizational structure, finances, legal issues, self-marketing, standards and accountability. Project coordination topics will include;account service and management, marketing, project tracking, personnel supervision and external services supervision. Creative topics will include creative direction in visual communication, visual and verbal problem solving, and traditional fine arts skills. Technology topics will include technology management and financing as well as mass market publishing technologies.' },
      { 'course_number' => '4800', 'credit_hours' => '3', 'name' => 'Advanced Study in Studio Art', 'course_description' => 'An optional course for students in the B.F.A. program (required of Graphic Design majors). Students may work in any art-related employment, such as advertising, publishing, or galleries and earn university credit. Gen. Ed. Designation: EL (I – Internships, Clinicals, Practica).' },
      { 'course_number' => '4900', 'credit_hours' => '3', 'name' => 'Senior Exhibition / Portfolio', 'course_description' => 'This course is for all graduating art majors. The objective is to develop the skills and impart the information necessary for being a working artist or designer, culminating in an exit review in the form of a formal portfolio review for Design Communications majors and a gallery exhibition for Studio and Art Education majors. Design Communications majors may also have a gallery exhibition. Students will develop a resume, business card, and promotional material and gain first-hand experience working with printers and other professional resources. Students will focus and get advice on the formal development-planning, preparation, execution- of their portfolio or exhibit. In addition, career-oriented discussions in a seminar atmosphere will relate to concerns and issues in the professional art and design world including but not limited to graduate school, job searches, networking as well as visits to area galleries, studios, and design firms. Upon the completion of the course, students are required to submit a slide portfolio and copies of their printed collateral (resume, business card, and self-promotional piece) in addition to their exit portfolio/exhibit. This course is offered in the spring semester only and should be taken in the spring semester prior to graduation. Gen. Ed. Designation: EL (P – Recitals, Shows, Exhibits).'}
    ].collect do |course|
      c = Course.new(course)
      c.level = "Freshman"  if ( c.course_number.to_i > 999  and c.course_number.to_i < 2000 )
      c.level = "Sophomore" if ( c.course_number.to_i > 1999 and c.course_number.to_i < 3000 )
      c.level = "Junior"    if ( c.course_number.to_i > 2999 and c.course_number.to_i < 4000 )
      c.level = "Senior"    if ( c.course_number.to_i > 3999 and c.course_number.to_i < 5000 )
      c.save
    end
  end
end